@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Container(socialNetwork, "Social Network", "K8S cluster", "Social Network System")

Rel(user, socialNetwork, "User makes request to the social network system")
@enduml