// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

// Replication:
// - master-slave (one sync + async)
// - replication factor 3
//
// Sharding:
// - key based by user id

Table User {
  id integer [primary key]
  name varchar
  description text
  photo_id integer [note: 'Photo is located in the file storage']
  city varchar
  interests text
  created_at timestamp
  updated_at timestamp
}