// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table User {
  id integer [primary key]
  name varchar
  description text
  photo_id integer [note: 'Photo is located in the file storage']
  city varchar
  interests text
  created_at timestamp
  updated_at timestamp
}